// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.24.0
// source: combined_fields.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const createCombinedField = `-- name: CreateCombinedField :exec
INSERT INTO combined_fields (user_id, combined_field)
VALUES ($1, '')
`

func (q *Queries) CreateCombinedField(ctx context.Context, userID uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, createCombinedField, userID)
	return err
}
