// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.24.0
// source: credential_access.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/lib/pq"
)

const addCredentialAccess = `-- name: AddCredentialAccess :one
INSERT INTO credential_access (credential_id, user_id, access_type, group_id, folder_id)
VALUES ($1, $2, $3, $4, $5)
RETURNING id
`

type AddCredentialAccessParams struct {
	CredentialID uuid.UUID     `json:"credentialId"`
	UserID       uuid.UUID     `json:"userId"`
	AccessType   string        `json:"accessType"`
	GroupID      uuid.NullUUID `json:"groupId"`
	FolderID     uuid.NullUUID `json:"folderId"`
}

func (q *Queries) AddCredentialAccess(ctx context.Context, arg AddCredentialAccessParams) (uuid.UUID, error) {
	row := q.db.QueryRowContext(ctx, addCredentialAccess,
		arg.CredentialID,
		arg.UserID,
		arg.AccessType,
		arg.GroupID,
		arg.FolderID,
	)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const checkCredentialAccessEntryExists = `-- name: CheckCredentialAccessEntryExists :one
SELECT EXISTS (
    SELECT 1
    FROM credential_access
    WHERE user_id = $1 AND credential_id = $2 
    AND ((group_id IS NOT NULL AND group_id = $3) OR (group_id is null and $3 is null)) 
    AND ((folder_id IS NOT NULL AND folder_id = $4) OR (folder_id is null and $4 is null))
)
`

type CheckCredentialAccessEntryExistsParams struct {
	UserID       uuid.UUID     `json:"userId"`
	CredentialID uuid.UUID     `json:"credentialId"`
	GroupID      uuid.NullUUID `json:"groupId"`
	FolderID     uuid.NullUUID `json:"folderId"`
}

func (q *Queries) CheckCredentialAccessEntryExists(ctx context.Context, arg CheckCredentialAccessEntryExistsParams) (bool, error) {
	row := q.db.QueryRowContext(ctx, checkCredentialAccessEntryExists,
		arg.UserID,
		arg.CredentialID,
		arg.GroupID,
		arg.FolderID,
	)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const editCredentialAccessForGroup = `-- name: EditCredentialAccessForGroup :exec
UPDATE credential_access
SET access_type = $1
WHERE folder_id IS NULL
AND credential_id = $2 AND group_id = $3
`

type EditCredentialAccessForGroupParams struct {
	AccessType   string        `json:"accessType"`
	CredentialID uuid.UUID     `json:"credentialId"`
	GroupID      uuid.NullUUID `json:"groupId"`
}

func (q *Queries) EditCredentialAccessForGroup(ctx context.Context, arg EditCredentialAccessForGroupParams) error {
	_, err := q.db.ExecContext(ctx, editCredentialAccessForGroup, arg.AccessType, arg.CredentialID, arg.GroupID)
	return err
}

const editCredentialAccessForGroupWithFolderID = `-- name: EditCredentialAccessForGroupWithFolderID :exec
UPDATE credential_access
SET access_type = $1
WHERE folder_id = $2 AND group_id = $3
`

type EditCredentialAccessForGroupWithFolderIDParams struct {
	AccessType string        `json:"accessType"`
	FolderID   uuid.NullUUID `json:"folderId"`
	GroupID    uuid.NullUUID `json:"groupId"`
}

func (q *Queries) EditCredentialAccessForGroupWithFolderID(ctx context.Context, arg EditCredentialAccessForGroupWithFolderIDParams) error {
	_, err := q.db.ExecContext(ctx, editCredentialAccessForGroupWithFolderID, arg.AccessType, arg.FolderID, arg.GroupID)
	return err
}

const editCredentialAccessForUser = `-- name: EditCredentialAccessForUser :exec
UPDATE credential_access
SET access_type = $1
WHERE  group_id IS NULL AND folder_id IS NULL
AND credential_id = $2 AND user_id = $3
`

type EditCredentialAccessForUserParams struct {
	AccessType   string    `json:"accessType"`
	CredentialID uuid.UUID `json:"credentialId"`
	UserID       uuid.UUID `json:"userId"`
}

func (q *Queries) EditCredentialAccessForUser(ctx context.Context, arg EditCredentialAccessForUserParams) error {
	_, err := q.db.ExecContext(ctx, editCredentialAccessForUser, arg.AccessType, arg.CredentialID, arg.UserID)
	return err
}

const editCredentialAccessForUserWithFolderID = `-- name: EditCredentialAccessForUserWithFolderID :exec
UPDATE credential_access
SET access_type = $1
WHERE group_id IS NULL
AND folder_id = $2 AND user_id = $3
`

type EditCredentialAccessForUserWithFolderIDParams struct {
	AccessType string        `json:"accessType"`
	FolderID   uuid.NullUUID `json:"folderId"`
	UserID     uuid.UUID     `json:"userId"`
}

func (q *Queries) EditCredentialAccessForUserWithFolderID(ctx context.Context, arg EditCredentialAccessForUserWithFolderIDParams) error {
	_, err := q.db.ExecContext(ctx, editCredentialAccessForUserWithFolderID, arg.AccessType, arg.FolderID, arg.UserID)
	return err
}

const getCredentialAccessTypeForUser = `-- name: GetCredentialAccessTypeForUser :many
SELECT id, user_id, credential_id, group_id, access_type
FROM credential_access
WHERE user_id = $1 AND credential_id = $2
`

type GetCredentialAccessTypeForUserParams struct {
	UserID       uuid.UUID `json:"userId"`
	CredentialID uuid.UUID `json:"credentialId"`
}

type GetCredentialAccessTypeForUserRow struct {
	ID           uuid.UUID     `json:"id"`
	UserID       uuid.UUID     `json:"userId"`
	CredentialID uuid.UUID     `json:"credentialId"`
	GroupID      uuid.NullUUID `json:"groupId"`
	AccessType   string        `json:"accessType"`
}

func (q *Queries) GetCredentialAccessTypeForUser(ctx context.Context, arg GetCredentialAccessTypeForUserParams) ([]GetCredentialAccessTypeForUserRow, error) {
	rows, err := q.db.QueryContext(ctx, getCredentialAccessTypeForUser, arg.UserID, arg.CredentialID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetCredentialAccessTypeForUserRow{}
	for rows.Next() {
		var i GetCredentialAccessTypeForUserRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.CredentialID,
			&i.GroupID,
			&i.AccessType,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCredentialGroups = `-- name: GetCredentialGroups :many
SELECT  DISTINCT
    ca.group_id,
    g.name,
    ca.access_type,
    CASE WHEN ca.folder_id IS NULL THEN 'acquired' ELSE 'inherited' END AS "accessSource"
FROM 
    credential_access ca
JOIN 
    groupings g ON g.id = ca.group_id
WHERE 
    ca.credential_id = $1
`

type GetCredentialGroupsRow struct {
	GroupID      uuid.NullUUID `json:"groupId"`
	Name         string        `json:"name"`
	AccessType   string        `json:"accessType"`
	AccessSource string        `json:"accessSource"`
}

func (q *Queries) GetCredentialGroups(ctx context.Context, credentialID uuid.UUID) ([]GetCredentialGroupsRow, error) {
	rows, err := q.db.QueryContext(ctx, getCredentialGroups, credentialID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetCredentialGroupsRow{}
	for rows.Next() {
		var i GetCredentialGroupsRow
		if err := rows.Scan(
			&i.GroupID,
			&i.Name,
			&i.AccessType,
			&i.AccessSource,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCredentialIDsByUserID = `-- name: GetCredentialIDsByUserID :many
SELECT credential_id FROM credential_access WHERE user_id = $1
`

func (q *Queries) GetCredentialIDsByUserID(ctx context.Context, userID uuid.UUID) ([]uuid.UUID, error) {
	rows, err := q.db.QueryContext(ctx, getCredentialIDsByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []uuid.UUID{}
	for rows.Next() {
		var credential_id uuid.UUID
		if err := rows.Scan(&credential_id); err != nil {
			return nil, err
		}
		items = append(items, credential_id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCredentialUsersForDataSync = `-- name: GetCredentialUsersForDataSync :many
SELECT 
    DISTINCT ca.user_id as "id",
    COALESCE(u.encryption_key, '') AS "publicKey"
FROM
    credential_access ca
JOIN
    users u ON ca.user_id = u.id
WHERE
    ca.credential_id = $1
`

type GetCredentialUsersForDataSyncRow struct {
	ID        uuid.UUID `json:"id"`
	PublicKey string    `json:"publicKey"`
}

func (q *Queries) GetCredentialUsersForDataSync(ctx context.Context, credentialID uuid.UUID) ([]GetCredentialUsersForDataSyncRow, error) {
	rows, err := q.db.QueryContext(ctx, getCredentialUsersForDataSync, credentialID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetCredentialUsersForDataSyncRow{}
	for rows.Next() {
		var i GetCredentialUsersForDataSyncRow
		if err := rows.Scan(&i.ID, &i.PublicKey); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCredentialUsersWithDirectAccess = `-- name: GetCredentialUsersWithDirectAccess :many
SELECT 
    ca.user_id,
    u.name,
    u.username,
    ca.access_type,
    CASE WHEN (ca.folder_id IS NULL AND ca.group_id is NULL) THEN 'acquired' ELSE 'inherited' END AS "accessSource"
FROM 
    credential_access ca
JOIN 
    users u ON ca.user_id = u.id
WHERE ca.credential_id = $1
`

type GetCredentialUsersWithDirectAccessRow struct {
	UserID       uuid.UUID `json:"userId"`
	Name         string    `json:"name"`
	Username     string    `json:"username"`
	AccessType   string    `json:"accessType"`
	AccessSource string    `json:"accessSource"`
}

func (q *Queries) GetCredentialUsersWithDirectAccess(ctx context.Context, credentialID uuid.UUID) ([]GetCredentialUsersWithDirectAccessRow, error) {
	rows, err := q.db.QueryContext(ctx, getCredentialUsersWithDirectAccess, credentialID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetCredentialUsersWithDirectAccessRow{}
	for rows.Next() {
		var i GetCredentialUsersWithDirectAccessRow
		if err := rows.Scan(
			&i.UserID,
			&i.Name,
			&i.Username,
			&i.AccessType,
			&i.AccessSource,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUsersByCredential = `-- name: GetUsersByCredential :many
SELECT users.id, users.username, users.name, COALESCE(users.encryption_key, '') as "publicKey", credential_access.access_type as "accessType"
FROM credential_access
JOIN users ON credential_access.user_id = users.id
WHERE credential_access.credential_id = $1
`

type GetUsersByCredentialRow struct {
	ID         uuid.UUID `json:"id"`
	Username   string    `json:"username"`
	Name       string    `json:"name"`
	PublicKey  string    `json:"publicKey"`
	AccessType string    `json:"accessType"`
}

func (q *Queries) GetUsersByCredential(ctx context.Context, credentialID uuid.UUID) ([]GetUsersByCredentialRow, error) {
	rows, err := q.db.QueryContext(ctx, getUsersByCredential, credentialID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetUsersByCredentialRow{}
	for rows.Next() {
		var i GetUsersByCredentialRow
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.Name,
			&i.PublicKey,
			&i.AccessType,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const hasManageAccessForCredential = `-- name: HasManageAccessForCredential :one
SELECT EXISTS (
  SELECT 1 FROM credential_access
  WHERE credential_id = $1 AND user_id = $2 AND access_type = 'manager'
)
`

type HasManageAccessForCredentialParams struct {
	CredentialID uuid.UUID `json:"credentialId"`
	UserID       uuid.UUID `json:"userId"`
}

func (q *Queries) HasManageAccessForCredential(ctx context.Context, arg HasManageAccessForCredentialParams) (bool, error) {
	row := q.db.QueryRowContext(ctx, hasManageAccessForCredential, arg.CredentialID, arg.UserID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const hasReadAccessForCredential = `-- name: HasReadAccessForCredential :one
SELECT EXISTS (
  SELECT 1 FROM credential_access
  WHERE credential_id = $1 AND user_id = $2 AND access_type IN ('reader', 'manager')
)
`

type HasReadAccessForCredentialParams struct {
	CredentialID uuid.UUID `json:"credentialId"`
	UserID       uuid.UUID `json:"userId"`
}

func (q *Queries) HasReadAccessForCredential(ctx context.Context, arg HasReadAccessForCredentialParams) (bool, error) {
	row := q.db.QueryRowContext(ctx, hasReadAccessForCredential, arg.CredentialID, arg.UserID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const removeCredentialAccessForGroupMember = `-- name: RemoveCredentialAccessForGroupMember :exec
DELETE FROM credential_access WHERE 
group_id = $1 AND user_id = $2
`

type RemoveCredentialAccessForGroupMemberParams struct {
	GroupID uuid.NullUUID `json:"groupId"`
	UserID  uuid.UUID     `json:"userId"`
}

func (q *Queries) RemoveCredentialAccessForGroupMember(ctx context.Context, arg RemoveCredentialAccessForGroupMemberParams) error {
	_, err := q.db.ExecContext(ctx, removeCredentialAccessForGroupMember, arg.GroupID, arg.UserID)
	return err
}

const removeCredentialAccessForGroups = `-- name: RemoveCredentialAccessForGroups :exec
DELETE FROM credential_access WHERE folder_id IS NULL 
AND credential_id = $1 AND group_id = ANY($2::UUID[])
`

type RemoveCredentialAccessForGroupsParams struct {
	CredentialID uuid.UUID   `json:"credentialId"`
	GroupIds     []uuid.UUID `json:"groupIds"`
}

func (q *Queries) RemoveCredentialAccessForGroups(ctx context.Context, arg RemoveCredentialAccessForGroupsParams) error {
	_, err := q.db.ExecContext(ctx, removeCredentialAccessForGroups, arg.CredentialID, pq.Array(arg.GroupIds))
	return err
}

const removeCredentialAccessForGroupsWithFolderID = `-- name: RemoveCredentialAccessForGroupsWithFolderID :exec
DELETE FROM credential_access WHERE folder_id = $1 AND group_id = ANY($2::UUID[])
`

type RemoveCredentialAccessForGroupsWithFolderIDParams struct {
	FolderID uuid.NullUUID `json:"folderId"`
	GroupIds []uuid.UUID   `json:"groupIds"`
}

func (q *Queries) RemoveCredentialAccessForGroupsWithFolderID(ctx context.Context, arg RemoveCredentialAccessForGroupsWithFolderIDParams) error {
	_, err := q.db.ExecContext(ctx, removeCredentialAccessForGroupsWithFolderID, arg.FolderID, pq.Array(arg.GroupIds))
	return err
}

const removeCredentialAccessForUsers = `-- name: RemoveCredentialAccessForUsers :exec
DELETE FROM credential_access WHERE group_id IS NULL AND folder_id IS NULL 
AND credential_id = $1 AND user_id = ANY($2::UUID[])
`

type RemoveCredentialAccessForUsersParams struct {
	CredentialID uuid.UUID   `json:"credentialId"`
	UserIds      []uuid.UUID `json:"userIds"`
}

func (q *Queries) RemoveCredentialAccessForUsers(ctx context.Context, arg RemoveCredentialAccessForUsersParams) error {
	_, err := q.db.ExecContext(ctx, removeCredentialAccessForUsers, arg.CredentialID, pq.Array(arg.UserIds))
	return err
}

const removeCredentialAccessForUsersWithFolderID = `-- name: RemoveCredentialAccessForUsersWithFolderID :exec
DELETE FROM credential_access WHERE group_id IS NULL
AND folder_id = $1 AND user_id = ANY($2::UUID[])
`

type RemoveCredentialAccessForUsersWithFolderIDParams struct {
	FolderID uuid.NullUUID `json:"folderId"`
	UserIds  []uuid.UUID   `json:"userIds"`
}

func (q *Queries) RemoveCredentialAccessForUsersWithFolderID(ctx context.Context, arg RemoveCredentialAccessForUsersWithFolderIDParams) error {
	_, err := q.db.ExecContext(ctx, removeCredentialAccessForUsersWithFolderID, arg.FolderID, pq.Array(arg.UserIds))
	return err
}
