// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.24.0
// source: field_values.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const addFieldValue = `-- name: AddFieldValue :exec
INSERT INTO field_values (field_id, field_value, user_id)
VALUES ($1, $2, $3)
`

type AddFieldValueParams struct {
	FieldID    uuid.UUID `json:"fieldId"`
	FieldValue string    `json:"fieldValue"`
	UserID     uuid.UUID `json:"userId"`
}

func (q *Queries) AddFieldValue(ctx context.Context, arg AddFieldValueParams) error {
	_, err := q.db.ExecContext(ctx, addFieldValue, arg.FieldID, arg.FieldValue, arg.UserID)
	return err
}
