// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.24.0
// source: field.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/lib/pq"
)

const addFieldData = `-- name: AddFieldData :one
INSERT INTO
    fields (field_name, field_value, credential_id, field_type, user_id)
VALUES
    ($1, $2, $3, $4, $5) RETURNING id
`

type AddFieldDataParams struct {
	FieldName    string    `json:"fieldName"`
	FieldValue   string    `json:"fieldValue"`
	CredentialID uuid.UUID `json:"credentialId"`
	FieldType    string    `json:"fieldType"`
	UserID       uuid.UUID `json:"userId"`
}

func (q *Queries) AddFieldData(ctx context.Context, arg AddFieldDataParams) (uuid.UUID, error) {
	row := q.db.QueryRowContext(ctx, addFieldData,
		arg.FieldName,
		arg.FieldValue,
		arg.CredentialID,
		arg.FieldType,
		arg.UserID,
	)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const checkFieldEntryExists = `-- name: CheckFieldEntryExists :one
SELECT EXISTS (
    SELECT 1
    FROM fields
    WHERE credential_id = $1 AND user_id = $2
)
`

type CheckFieldEntryExistsParams struct {
	CredentialID uuid.UUID `json:"credentialId"`
	UserID       uuid.UUID `json:"userId"`
}

func (q *Queries) CheckFieldEntryExists(ctx context.Context, arg CheckFieldEntryExistsParams) (bool, error) {
	row := q.db.QueryRowContext(ctx, checkFieldEntryExists, arg.CredentialID, arg.UserID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const fetchEncryptedFieldsByCredentialIDAndUserID = `-- name: FetchEncryptedFieldsByCredentialIDAndUserID :many
SELECT
    id,
    field_name,
    field_value
FROM
    fields
WHERE
    credential_id = $1
    AND user_id = $2
`

type FetchEncryptedFieldsByCredentialIDAndUserIDParams struct {
	CredentialID uuid.UUID `json:"credentialId"`
	UserID       uuid.UUID `json:"userId"`
}

type FetchEncryptedFieldsByCredentialIDAndUserIDRow struct {
	ID         uuid.UUID `json:"id"`
	FieldName  string    `json:"fieldName"`
	FieldValue string    `json:"fieldValue"`
}

func (q *Queries) FetchEncryptedFieldsByCredentialIDAndUserID(ctx context.Context, arg FetchEncryptedFieldsByCredentialIDAndUserIDParams) ([]FetchEncryptedFieldsByCredentialIDAndUserIDRow, error) {
	rows, err := q.db.QueryContext(ctx, fetchEncryptedFieldsByCredentialIDAndUserID, arg.CredentialID, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []FetchEncryptedFieldsByCredentialIDAndUserIDRow{}
	for rows.Next() {
		var i FetchEncryptedFieldsByCredentialIDAndUserIDRow
		if err := rows.Scan(&i.ID, &i.FieldName, &i.FieldValue); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getFieldDataByCredentialIDsForUser = `-- name: GetFieldDataByCredentialIDsForUser :many
SELECT
    f.id,
    f.credential_id,
    f.field_name,
    f.field_value,
    f.field_type
FROM fields as f
WHERE f.user_id = $1 
AND f.credential_id = ANY($2::UUID[])
`

type GetFieldDataByCredentialIDsForUserParams struct {
	UserID      uuid.UUID   `json:"userId"`
	Credentials []uuid.UUID `json:"credentials"`
}

type GetFieldDataByCredentialIDsForUserRow struct {
	ID           uuid.UUID `json:"id"`
	CredentialID uuid.UUID `json:"credentialId"`
	FieldName    string    `json:"fieldName"`
	FieldValue   string    `json:"fieldValue"`
	FieldType    string    `json:"fieldType"`
}

func (q *Queries) GetFieldDataByCredentialIDsForUser(ctx context.Context, arg GetFieldDataByCredentialIDsForUserParams) ([]GetFieldDataByCredentialIDsForUserRow, error) {
	rows, err := q.db.QueryContext(ctx, getFieldDataByCredentialIDsForUser, arg.UserID, pq.Array(arg.Credentials))
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetFieldDataByCredentialIDsForUserRow{}
	for rows.Next() {
		var i GetFieldDataByCredentialIDsForUserRow
		if err := rows.Scan(
			&i.ID,
			&i.CredentialID,
			&i.FieldName,
			&i.FieldValue,
			&i.FieldType,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
