// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: folder_access.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/lib/pq"
)

const addFolderAccess = `-- name: AddFolderAccess :exec
INSERT INTO folder_access (folder_id, user_id, access_type, group_id)
VALUES ($1, $2, $3, $4)
`

type AddFolderAccessParams struct {
	FolderID   uuid.UUID     `json:"folderId"`
	UserID     uuid.UUID     `json:"userId"`
	AccessType string        `json:"accessType"`
	GroupID    uuid.NullUUID `json:"groupId"`
}

func (q *Queries) AddFolderAccess(ctx context.Context, arg AddFolderAccessParams) error {
	_, err := q.db.ExecContext(ctx, addFolderAccess,
		arg.FolderID,
		arg.UserID,
		arg.AccessType,
		arg.GroupID,
	)
	return err
}

const checkFolderAccessEntryExists = `-- name: CheckFolderAccessEntryExists :one
SELECT EXISTS (
    SELECT 1
    FROM folder_access
    WHERE user_id = $1 AND folder_id = $2 
    AND ((group_id IS NOT NULL AND group_id = $3) OR (group_id is null and $3 is null)) 
)
`

type CheckFolderAccessEntryExistsParams struct {
	UserID   uuid.UUID     `json:"userId"`
	FolderID uuid.UUID     `json:"folderId"`
	GroupID  uuid.NullUUID `json:"groupId"`
}

func (q *Queries) CheckFolderAccessEntryExists(ctx context.Context, arg CheckFolderAccessEntryExistsParams) (bool, error) {
	row := q.db.QueryRowContext(ctx, checkFolderAccessEntryExists, arg.UserID, arg.FolderID, arg.GroupID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const editFolderAccessForGroup = `-- name: EditFolderAccessForGroup :exec
UPDATE folder_access
SET access_type = $1
WHERE folder_id = $2 AND group_id = $3
`

type EditFolderAccessForGroupParams struct {
	AccessType string        `json:"accessType"`
	FolderID   uuid.UUID     `json:"folderId"`
	GroupID    uuid.NullUUID `json:"groupId"`
}

func (q *Queries) EditFolderAccessForGroup(ctx context.Context, arg EditFolderAccessForGroupParams) error {
	_, err := q.db.ExecContext(ctx, editFolderAccessForGroup, arg.AccessType, arg.FolderID, arg.GroupID)
	return err
}

const editFolderAccessForUser = `-- name: EditFolderAccessForUser :exec
UPDATE folder_access
SET access_type = $1
WHERE group_id IS NULL
AND folder_id = $2 AND user_id = $3
`

type EditFolderAccessForUserParams struct {
	AccessType string    `json:"accessType"`
	FolderID   uuid.UUID `json:"folderId"`
	UserID     uuid.UUID `json:"userId"`
}

func (q *Queries) EditFolderAccessForUser(ctx context.Context, arg EditFolderAccessForUserParams) error {
	_, err := q.db.ExecContext(ctx, editFolderAccessForUser, arg.AccessType, arg.FolderID, arg.UserID)
	return err
}

const getFolderGroups = `-- name: GetFolderGroups :many
SELECT 
    DISTINCT fa.group_id,
    g.name,
    fa.access_type
FROM 
    folder_access fa
JOIN 
    groupings g ON g.id = fa.group_id
WHERE 
    fa.folder_id = $1
`

type GetFolderGroupsRow struct {
	GroupID    uuid.NullUUID `json:"groupId"`
	Name       string        `json:"name"`
	AccessType string        `json:"accessType"`
}

func (q *Queries) GetFolderGroups(ctx context.Context, folderID uuid.UUID) ([]GetFolderGroupsRow, error) {
	rows, err := q.db.QueryContext(ctx, getFolderGroups, folderID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetFolderGroupsRow{}
	for rows.Next() {
		var i GetFolderGroupsRow
		if err := rows.Scan(&i.GroupID, &i.Name, &i.AccessType); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getFolderUsersForDataSync = `-- name: GetFolderUsersForDataSync :many
SELECT 
    DISTINCT fa.user_id as "id",
    COALESCE(u.encryption_key, '') AS "publicKey"
FROM
    folder_access fa
JOIN
    users u ON fa.user_id = u.id
WHERE
    fa.folder_id = $1
`

type GetFolderUsersForDataSyncRow struct {
	ID        uuid.UUID `json:"id"`
	PublicKey string    `json:"publicKey"`
}

func (q *Queries) GetFolderUsersForDataSync(ctx context.Context, folderID uuid.UUID) ([]GetFolderUsersForDataSyncRow, error) {
	rows, err := q.db.QueryContext(ctx, getFolderUsersForDataSync, folderID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetFolderUsersForDataSyncRow{}
	for rows.Next() {
		var i GetFolderUsersForDataSyncRow
		if err := rows.Scan(&i.ID, &i.PublicKey); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getFolderUsersWithDirectAccess = `-- name: GetFolderUsersWithDirectAccess :many
SELECT 
    fa.user_id,
    u.name,
    u.username,
    fa.access_type,
    CASE WHEN (fa.group_id is NULL) THEN 'acquired' ELSE 'inherited' END AS "accessSource"
FROM 
    folder_access fa
JOIN 
    users u ON fa.user_id = u.id
WHERE 
    fa.folder_id = $1
`

type GetFolderUsersWithDirectAccessRow struct {
	UserID       uuid.UUID `json:"userId"`
	Name         string    `json:"name"`
	Username     string    `json:"username"`
	AccessType   string    `json:"accessType"`
	AccessSource string    `json:"accessSource"`
}

func (q *Queries) GetFolderUsersWithDirectAccess(ctx context.Context, folderID uuid.UUID) ([]GetFolderUsersWithDirectAccessRow, error) {
	rows, err := q.db.QueryContext(ctx, getFolderUsersWithDirectAccess, folderID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetFolderUsersWithDirectAccessRow{}
	for rows.Next() {
		var i GetFolderUsersWithDirectAccessRow
		if err := rows.Scan(
			&i.UserID,
			&i.Name,
			&i.Username,
			&i.AccessType,
			&i.AccessSource,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const hasManageAccessForFolder = `-- name: HasManageAccessForFolder :one
SELECT EXISTS (
  SELECT 1 FROM folder_access
  WHERE folder_id = $1 AND user_id = $2 AND access_type = 'manager'
)
`

type HasManageAccessForFolderParams struct {
	FolderID uuid.UUID `json:"folderId"`
	UserID   uuid.UUID `json:"userId"`
}

func (q *Queries) HasManageAccessForFolder(ctx context.Context, arg HasManageAccessForFolderParams) (bool, error) {
	row := q.db.QueryRowContext(ctx, hasManageAccessForFolder, arg.FolderID, arg.UserID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const hasReadAccessForFolder = `-- name: HasReadAccessForFolder :one
SELECT EXISTS (
  SELECT 1 FROM folder_access
  WHERE folder_id = $1 AND user_id = $2 AND access_type IN ('manager', 'reader')
)
`

type HasReadAccessForFolderParams struct {
	FolderID uuid.UUID `json:"folderId"`
	UserID   uuid.UUID `json:"userId"`
}

func (q *Queries) HasReadAccessForFolder(ctx context.Context, arg HasReadAccessForFolderParams) (bool, error) {
	row := q.db.QueryRowContext(ctx, hasReadAccessForFolder, arg.FolderID, arg.UserID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const removeFolderAccessForGroupMember = `-- name: RemoveFolderAccessForGroupMember :exec
DELETE FROM folder_access WHERE 
group_id = $1 AND user_id = $2
`

type RemoveFolderAccessForGroupMemberParams struct {
	GroupID uuid.NullUUID `json:"groupId"`
	UserID  uuid.UUID     `json:"userId"`
}

func (q *Queries) RemoveFolderAccessForGroupMember(ctx context.Context, arg RemoveFolderAccessForGroupMemberParams) error {
	_, err := q.db.ExecContext(ctx, removeFolderAccessForGroupMember, arg.GroupID, arg.UserID)
	return err
}

const removeFolderAccessForGroups = `-- name: RemoveFolderAccessForGroups :exec
DELETE FROM folder_access WHERE folder_id = $1 AND group_id = ANY($2::UUID[])
`

type RemoveFolderAccessForGroupsParams struct {
	FolderID uuid.UUID   `json:"folderId"`
	GroupIds []uuid.UUID `json:"groupIds"`
}

func (q *Queries) RemoveFolderAccessForGroups(ctx context.Context, arg RemoveFolderAccessForGroupsParams) error {
	_, err := q.db.ExecContext(ctx, removeFolderAccessForGroups, arg.FolderID, pq.Array(arg.GroupIds))
	return err
}

const removeFolderAccessForUsers = `-- name: RemoveFolderAccessForUsers :exec
DELETE FROM folder_access WHERE group_id IS NULL 
AND folder_id = $1 AND user_id = ANY($2::UUID[])
`

type RemoveFolderAccessForUsersParams struct {
	FolderID uuid.UUID   `json:"folderId"`
	UserIds  []uuid.UUID `json:"userIds"`
}

func (q *Queries) RemoveFolderAccessForUsers(ctx context.Context, arg RemoveFolderAccessForUsersParams) error {
	_, err := q.db.ExecContext(ctx, removeFolderAccessForUsers, arg.FolderID, pq.Array(arg.UserIds))
	return err
}
